version: '3'
services:
  APP_NAME:
    image: wordpress
    restart: always
    container_name: APP_NAME
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: HOST_NAME
      WORDPRESS_DB_HOST: host.docker.internal
      WORDPRESS_DB_USER: native
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: APP_NAME
    volumes:
      - .:/var/www/html

networks:
  default:
    external:
      name: develop