version: '3'
services:
  APP_NAME:
    image: php:7-apache
    restart: always
    container_name: APP_NAME
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: HOST_NAME
    volumes:
      - .:/var/www/html

networks:
  default:
    external:
      name: develop