name: Update Formura

on:
  push:
#     tags:
#       - '*'

jobs:
  update-formura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Checkout Formura Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ken109/homebrew-lcl
          path: formura

      - name: Ls
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
          cat formura/templete.rb
