name: Update Formura

on:
  push:
    tags:
      - '*'

jobs:
  update-formura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Get SHA256
        id: get_sha256
        run: |
          wget https://github.com/ken109/lcl/archive/${{ steps.get_version.outputs.VERSION }}.tar.gz
          echo ::set-output name=SHA256::$(openssl dgst -r -SHA256 ${{ steps.get_version.outputs.VERSION }}.tar.gz | cut -d ' ' -f 1)

      - name: Checkout Formura Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ken109/homebrew-lcl
          path: formura

      - name: Update Formura
        run: |
          sed s/+VIRSION+/${{ steps.get_version.outputs.VERSION }}/ ./formura/templete.rb > ./formura/lcl.rb
          sed -i s/+SHA256+/${{ steps.get_sha256.outputs.SHA256 }}/ ./formura/lcl.rb

      - name: Setup git repogitories
        run: |
          echo "{{ secrets.DEPLOY_KEY }}" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --global user.email "kensukekubo19@gmail.com"
          git config --global user.name "Kensuke Kubo"
          cd formura
          git remote set-url origin git@github.com:ken109/homebrew-lcl.git
          git checkout master
        
      - name: Push Formura
        run: |
          cd formura
          git add .
          git commit -m 'Formura ${{ steps.get_version.outputs.VERSION }}'
          git push origin master
